server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest-api-db
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: ajay
      password: ajay